"""
策略检查项危害等级配置
"""

POLICY_HAZARD_LEVEL = {
    # ════════════════════ AF ════════════════════

    # P0 致命
    "AF_BYPASS": "P0",
    "AF_BY_PASS": "P0",
    "AF_BYPASS_POLICY": "P0",
    "AF_IPS": "P0",
    "AF_WEB_APP_PROTECT": "P0",
    "AF_WEB_APP_PROTECT_PATTERN": "P0",
    "AF_BOT_NET": "P0",
    "AF_RANSOM_PORT": "P0",
    "AF_PORT_REFLECTION": "P0",
    "AF_OFFLINE": "P0",
    "AF_SERIAL_NUMBER": "P0",

    # P2 中危
    "AF_RULE_LIB": "P2",
    "AF_VIRUS_ENGINE_UPDATE": "P2",
    "AF_GATEWAY_VIRUS": "P2",
    "AF_DECRYPT_CONFIG": "P2",
    "AF_CUSTOM_WHITELIST": "P2",
    "AF_WEB_COMMAND_BLASS_PROTECT": "P2",
    "AF_LATEST_THREAT": "P2",
    "AF_BASE_FUNCTION": "P2",
    "AF_ENHANCE_FUNCTION": "P2",
    "AF_HONEY_POT": "P2",
    "AF_IPS_PROTECT_PATTERN": "P2",

    # P3 低危
    "AF_FUNCTION_PATTERN": "P3",
    "AF_PROTECT_OBJECT": "P3",
    "AF_IPV4_TRANSFORM": "P3",
    "AF_SECURITY_DEFENSE_LOG": "P3",
    "AF_LOG_UPLOAD": "P3",
    "AF_VERSION": "P3",

    # ════════════════════ EDR ════════════════════

    # P0 致命
    "EDR_WINDOWS_FILE_MONITOR_ENABLE": "P0",
    "TYPE_EDR_LINUX_REALTIME_FILE_PROTECTION": "P0",

    # P1 高危
    "EDR_WINDOWS_RANSOM_KILLER_ENABLE": "P1",
    "EDR_WINDOWS_RANSOM_KILLER_HANDLE": "P1",
    "EDR_LINUX_WEBSHELL_SCAN_ENABLE": "P1",
    "EDR_WINDOWS_WEBSHELL_SCAN_ENABLE": "P1",
    "EDR_WINDOWS_POWERSHELL_ENABLE": "P1",
    "EDR_WINDOWS_ANTI_BFA_RDP_ENABLE": "P1",
    "EDR_WINDOWS_ANTI_BFA_SMB_ENABLE": "P1",
    "EDR_LINUX_ANTI_BFA_SSH_ENABLE": "P1",
    "EDR_WINDOWS_REMOTE_PRETECT": "P1",
    "EDR_WINDOWS_PASSWORD": "P1",
    "EDR_VIRUS_LIB_CHECK": "P1",
    "EDR_VUL_LIB_CHECK": "P1",

    # P2 中危
    "EDR_WINDOWS_FILE_MONITOR_PROTECT_LEVEL": "P2",
    "EDR_WINDOWS_FILE_MONITOR_MALICE_FILE": "P2",
    "EDR_WINDOWS_POWERSHELL_HANDLE": "P2",
    "EDR_WINDOWS_ANTI_BFA_RDP_METHOD": "P2",
    "EDR_WINDOWS_ANTI_BFA_SMB_METHOD": "P2",
    "EDR_LINUX_ANTI_BFA_SSH_HANDLE": "P2",
    "EDR_LINUX_WEBSHELL_SCAN_CHECK_METHOD": "P2",
    "EDR_LINUX_WEBSHELL_SCAN_HANDLE": "P2",
    "EDR_WINDOWS_WEBSHELL_SCAN_HANDLE": "P2",
    "EDR_WINDOWS_WEBSHELL_SCAN_METHOD": "P2",
    "EDR_LINUX_WEBSHELL_SCAN": "P2",
    "EDR_WINDOWS_WEBSHELL_SCAN": "P2",
    "EDR_WINDOWS_FILE_MONITOR_FILE_TYPE": "P2",
    "EDR_WINDOWS_FILE_MONITOR_ENGINE_CONFIG": "P2",
    "EDR_WINDOWS_AVSCAN_SET_LOCK": "P2",
    "EDR_WINDOWS_AVSCAN_MALICE_FILE": "P2",
    "EDR_LINUX_AVSCAN_MALICE_FILE": "P2",
    "TYPE_EDR_LINUX_REALTIME_FILE_PROTECTION_LEVEL": "P2",
    "TYPE_EDR_LINUX_REALTIME_FILE_DSP_MODEL": "P2",
    "EDR_WINDOWS_SCAN": "P2",
    "EDR_LINUX_SCAN": "P2",

    # P3 低危
    "EDR_VERSION": "P3",
    "EDR_SERIAL_NUMBER": "P3",
    "EDR_OFFLINE": "P3",

    # ════════════════════ AES ════════════════════

    # P0 致命
    "AES_WINDOWS_FILE_MONITOR_ENABLE": "P0",
    "TYPE_AES_LINUX_REALTIME_FILE_PROTECTION": "P0",

    # P1 高危
    "AES_WINDOWS_RANSOM_KILLER_ENABLE": "P1",
    "AES_WINDOWS_RANSOM_KILLER_HANDLE": "P1",
    "AES_LINUX_WEBSHELL_SCAN_ENABLE": "P1",
    "AES_WINDOWS_WEBSHELL_SCAN_ENABLE": "P1",
    "AES_WINDOWS_POWERSHELL_ENABLE": "P1",
    "AES_WINDOWS_ANTI_BFA_RDP_ENABLE": "P1",
    "AES_WINDOWS_ANTI_BFA_SMB_ENABLE": "P1",
    "AES_LINUX_ANTI_BFA_SSH_ENABLE": "P1",
    "AES_WINDOWS_REMOTE_PRETECT": "P1",
    "AES_WINDOWS_PASSWORD": "P1",
    "AES_VIRUS_LIB_CHECK": "P1",
    "AES_VUL_LIB_CHECK": "P1",

    # P2 中危
    "AES_WINDOWS_FILE_MONITOR_PROTECT_LEVEL": "P2",
    "AES_WINDOWS_FILE_MONITOR_MALICE_FILE": "P2",
    "AES_WINDOWS_POWERSHELL_HANDLE": "P2",
    "AES_WINDOWS_ANTI_BFA_RDP_METHOD": "P2",
    "AES_WINDOWS_ANTI_BFA_SMB_METHOD": "P2",
    "AES_LINUX_ANTI_BFA_SSH_HANDLE": "P2",
    "AES_LINUX_WEBSHELL_SCAN_CHECK_METHOD": "P2",
    "AES_LINUX_WEBSHELL_SCAN_HANDLE": "P2",
    "AES_WINDOWS_WEBSHELL_SCAN_HANDLE": "P2",
    "AES_WINDOWS_WEBSHELL_SCAN_METHOD": "P2",
    "AES_LINUX_WEBSHELL_SCAN": "P2",
    "AES_WINDOWS_WEBSHELL_SCAN": "P2",
    "AES_WINDOWS_FILE_MONITOR_FILE_TYPE": "P2",
    "AES_WINDOWS_FILE_MONITOR_ENGINE_CONFIG": "P2",
    "AES_WINDOWS_AVSCAN_SET_LOCK": "P2",
    "AES_WINDOWS_AVSCAN_MALICE_FILE": "P2",
    "AES_LINUX_AVSCAN_MALICE_FILE": "P2",
    "TYPE_AES_LINUX_REALTIME_FILE_PROTECTION_LEVEL": "P2",
    "TYPE_AES_LINUX_REALTIME_FILE_DSP_MODEL": "P2",
    "AES_WINDOWS_SCAN": "P2",
    "AES_LINUX_SCAN": "P2",

    # P3 低危
    "AES_VERSION": "P3",
    "AES_SERIAL_NUMBER": "P3",

    # ════════════════════ SIP ════════════════════

    # P2 中危
    "SIP_RULE_LIB": "P2",
    "SIP_HTTPFLOW_ANALYSIS": "P2",
    "SIP_STA_LOG_TRANS_MODE": "P2",

    # P3 低危
    "SIP_VERSION": "P3",
    "SIP_SERIAL_NUMBER": "P3",
    "SIP_SERIAL_NUMBER_NEW": "P3",
    "SIP_LOG_UPLOAD": "P3",
    "SIP_LOG_UPLOAD_NEW": "P3",
    "SIP_OFFLINE": "P3",

    # ════════════════════ TSS ════════════════════

    # P3 低危
    "TSS_SOFTWARE_CHECK": "P3",
    "TSS_LOOPHOLE_CHECK": "P3",

    # ════════════════════ CWPP ════════════════════

    # P0 致命
    "CWPP_VIRUS_DEFENSE_REAL_TIME_PROTECTION": "P0",
    "CWPP_VUL_DETECTION": "P0",

    # P1 高危
    "CWPP_INVADE_RULE_LIB": "P1",

    # P2 中危
    "CWPP_VIRUS_DEFENSE_MODE": "P2",
    "CWPP_VUL_RULE_LIB": "P2",

    # P3 低危
    "CWPP_VERSION": "P3",
    "CWPP_SERIAL_NUMBER": "P3",
}
